name: kitticlicker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  floating_animation: ^1.1.0

  cupertino_icons: ^1.0.8

  # State management (MVVM)
  provider: ^6.1.2

  #для апишки
  http: ^1.2.0

  # хранилище
  shared_preferences: ^2.0.0

  # Audio player для звуков
  audioplayers: ^6.1.0

  # Кэширование изображений из API
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter_native_splash:
  image: assets/icons/splash.png
  android: true
  ios: true
  android_gravity: center

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/images/kittens/
    - assets/images/skins/
    - assets/sounds/
  generate: true